### ISSUE TITLE
Interpretation of Figure 6

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#187]
Currently Figure 6 is cited for:

> the majority of the error comes from errors in the site-level mean

and also

>  none of the methods evaluated reliably determined whether site-level richness would increase or decrease over time [in contrast to: When comparing forecasts across sites, many different approaches to forecasting produce reasonable forecasts]

These seem contradictory from a first glance.

We either need to improve the language or pull this figure. We only really use it in the first paragraph of the discussion where a citation to Figure 4 would work equally well.

**Comment by davharris** [comment]
Another good catch! It's not a contradiction, but I can definitely see how it could seem that way.

They can both be true because the site-to-site variance starts off as something like 90% of the variance that's left after accounting for observer effects.  So even if we we can cut it by 80%, it's still the biggest source of error/variance.

To avoid a merge conflict, I'll wait to address this until after #189 goes in.
