### ISSUE TITLE
clarify table 1 description

### ISSUE THREAD

**Issue by sdtaylor** [weecology/bbs-forecasting#218]
reviewer 1 didn't understand this sentence. 

 Environmental models were trained using all sites together, without information regarding which transects occurred at which site or during which year.

How about:

Environmental models were trained using only the environmental data without information on the auto regressive time component or site random effects.

**Comment by davharris** [comment]
That's definitely clearer, but I think it's missing a couple of things.

* "*the auto regressive time component or site random effects*" is too specific, I think. It didn't just lack autoregressive effects and random effects: have *any* components at all for time or site.

* It doesn't specify that the models were trained at the continental scale instead of the site level.

I've poked at your sentence a bit, and haven't figured out how best to include these two factors.  Maybe we need two sentences?  Maybe we need a parenthetical with an "i.e." or an "e.g." somewhere ?

**Comment by sdtaylor** [comment]
maybe the original is confusing because of the word transect? I remember talking about taking transect out of the paper entirely because its essentially the same as site.

**Comment by sdtaylor** [comment]
Environmental models were each trained as a single continental scale model using only environmental variables as opposed to site or time series information.

**Comment by davharris** [comment]
Nice. How about this version?

Environmental models were trained at the continental scale, using only environmental variables (as opposed to site or time series information) as predictors.

**Comment by sdtaylor** [comment]
:+1:

**Comment by ethanwhite** [comment]
Closed by #220.
