### ISSUE TITLE
pre-1982 predictors?

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#79]
It looks like our NDVI and climate/weather data sets both start in 1982. I was wondering what our options were going before 1982 (especially for the bioclim variables).  Do we have that written down somewhere?

**Comment by davharris** [comment]
One option for climate could be the [NCEP/NCAR reanalysis](http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.surface.html). Supposedly, it can be downloaded automatically with the `FetchClimate` package.

**Comment by sdtaylor** [comment]
PRISM goes back to the beginning of BBS. NDVI goes to august 1981, and it's a pretty important predictor. Also remember that the BBS site density goes down pretty fast prior to 1980. 
![bbs_sites_per_year](https://cloud.githubusercontent.com/assets/12282062/18961755/135d0fbc-863c-11e6-909a-89da1aeb62c2.png)

**Comment by ethanwhite** [comment]
Following up on @sdtaylor's points with a touch more detail:

The real limitation here is NDVI and I'm not clear if we can get back any further directly. Landsat started in 1972 so if the multi-spectral reflectance data goes back to the beginning we might be able to get another decade with some work. If we could, that would be awesome. If not then we'd need to try to create a feature from the temp/precip data that was highly correlated with NDVI.

PRISM goes back to 1900. Pre-1982 is considered to be lower quality data because there are fewer weather stations available for the spatial krigging. It would just be a couple of tweaks to existing code to get it back as far as we want.

**Comment by davharris** [comment]
Okay, thanks both of you.  NDVI seems fairly constant (site_id explains >95% of the variance in ndvi_sum over the 32 years we currently have), so I'd feel fairly okay projecting that backward. Earlier PRISM data would be helpful, I think.

**Comment by ethanwhite** [comment]
This was a good discussion and we should keep this possibility in mind for future efforts.
